/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/DashBoard`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Motos`; params?: Router.UnknownInputParams; } | { pathname: `/Participantes`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FormLogin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Filial/[id_patio]`, params: Router.UnknownInputParams & { id_patio: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/DashBoard`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Motos`; params?: Router.UnknownOutputParams; } | { pathname: `/Participantes`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/FormLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Filial/[id_patio]`, params: Router.UnknownOutputParams & { id_patio: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Cadastro${`?${string}` | `#${string}` | ''}` | `/DashBoard${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Motos${`?${string}` | `#${string}` | ''}` | `/Participantes${`?${string}` | `#${string}` | ''}` | `/../components/FormLogin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/DashBoard`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Motos`; params?: Router.UnknownInputParams; } | { pathname: `/Participantes`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FormLogin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/Filial/${Router.SingleRoutePart<T>}` | { pathname: `/Filial/[id_patio]`, params: Router.UnknownInputParams & { id_patio: string | number; } };
    }
  }
}
